import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import Foooter from "@/components/layout/foooter";
import Heaader from "@/components/layout/heaader";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SoleSway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <Heaader />
      <main className="px-8">
        {children}
      </main>
      <Foooter/>
      <Footer/>
      </body>
    </html>
  );
}
